In [1]:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler, LabelEncoder 

In [4]:
df1 = pd.read_csv('meteo_juillet_decembre_2019.csv')
df2 = pd.read_csv('Travel_titles_with_departments.csv')

In [19]:
fusion = pd.merge(df1.rename(columns={'JOUR': 'DATE'}), df2, left_on='DATE', right_on='DATE' , how='inner')[lambda x: x['DEPARTEMENT'] == 75].reset_index(drop=True)
fusion["DATE"] = pd.to_datetime(fusion["DATE"])

In [20]:
fusion.head()

DATE  Précipitations  Humidité  Vent  Visibilité  Température  \
0 2019-07-01             0.0     59.35  4.24    19998.21        19.72   
1 2019-07-01             0.0     59.35  4.24    19998.21        19.72   
2 2019-07-01             0.0     59.35  4.24    19998.21        19.72   
3 2019-07-01             0.0     59.35  4.24    19998.21        19.72   
4 2019-07-01             0.0     59.35  4.24    19998.21        19.72   

   NB_VALID  DEPARTEMENT  
0      3399         75.0  
1     11480         75.0  
2      8288         75.0  
3      9007         75.0  
4      9262         75.0

In [21]:
fusion.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43270 entries, 0 to 43269
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   DATE            43270 non-null  datetime64[ns]
 1   Précipitations  43270 non-null  float64       
 2   Humidité        43270 non-null  float64       
 3   Vent            43270 non-null  float64       
 4   Visibilité      43270 non-null  float64       
 5   Température     43270 non-null  float64       
 6   NB_VALID        43270 non-null  int64         
 7   DEPARTEMENT     43270 non-null  float64       
dtypes: datetime64[ns](1), float64(6), int64(1)
memory usage: 2.6 MB


In [23]:
X = fusion.drop(["NB_VALID", "DATE"], axis=1) 
Y = fusion["NB_VALID"]

In [27]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, Y, test_size=0.2, random_state=42)

In [31]:
from sklearn.linear_model import LogisticRegression 
model = LogisticRegression(max_iter=1000) 

In [32]:
model.fit(X_train, y_train) 

LogisticRegression(max_iter=1000)

In [33]:
y_pred = model.predict(X_test) 

In [34]:
y_prob = model.predict_proba(X_test)[:,1]

In [36]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report 
print("Accuracy:", accuracy_score(y_test, y_pred)) 
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred)) 
print(classification_report(y_test, y_pred)) 

Accuracy: 0.02854171481395886
Confusion matrix:
 [[247   0   0 ...   0   0   0]
 [  6   0   0 ...   0   0   0]
 [  6   0   0 ...   0   0   0]
 ...
 [  1   0   0 ...   0   0   0]
 [  1   0   0 ...   0   0   0]
 [  1   0   0 ...   0   0   0]]
              precision    recall  f1-score   support

           5       0.03      1.00      0.06       248
           6       0.00      0.00      0.00         6
           7       0.00      0.00      0.00         6
           8       0.00      0.00      0.00        12
           9       0.00      0.00      0.00         5
          10       0.00      0.00      0.00        62
          11       0.00      0.00      0.00        10
          12       0.00      0.00      0.00         8
          13       0.00      0.00      0.00        10
          14       0.00      0.00      0.00         4
          15       0.00      0.00      0.00        20
          16       0.00      0.00      0.00         5
          17       0.00      0.00      0.00        11
  

C:\Users\alexa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\alexa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\alexa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classificati

In [37]:
from sklearn.metrics import mean_squared_error, r2_score 
print("MSE:", mean_squared_error(y_test, y_pred)) 
print("R2:", r2_score(y_test, y_pred)) 

MSE: 357707044.20764965
R2: -0.2988953941761876
